import type { Course, BlogPost, Testimonial } from "./types"

export const courses: Course[] = [
  {
    id: "1",
    title: "Complete Web Development Bootcamp",
    description: "Learn HTML, CSS, JavaScript, React, Node.js and more to become a full-stack web developer",
    price: 89.99,
    rating: 4.8,
    students: 15420,
    category: "Web Development",
    image: "/images/course-web-dev.png",
    instructor: "Sarah Johnson",
    duration: "12 weeks",
    level: "All Levels",
    isBestseller: true,
  },
  {
    id: "2",
    title: "Data Science and Machine Learning Masterclass",
    description: "Master data analysis, visualization, and machine learning algorithms with Python",
    price: 94.99,
    rating: 4.7,
    students: 8750,
    category: "Data Science",
    image: "/images/course-data-science.png",
    instructor: "Michael Chen",
    duration: "10 weeks",
    level: "Intermediate",
  },
  {
    id: "3",
    title: "UI/UX Design Fundamentals",
    description:
      "Learn the principles of user interface and user experience design to create beautiful, functional products",
    price: 79.99,
    rating: 4.9,
    students: 6320,
    category: "Design",
    image: "/images/course-ui-ux.png",
    instructor: "Emily Rodriguez",
    duration: "8 weeks",
    level: "Beginner",
    isNew: true,
  },
  {
    id: "4",
    title: "Mobile App Development with React Native",
    description: "Build cross-platform mobile applications for iOS and Android using React Native",
    price: 84.99,
    rating: 4.6,
    students: 5180,
    category: "Mobile Development",
    image: "/images/course-mobile-dev.png",
    instructor: "David Kim",
    duration: "9 weeks",
    level: "Intermediate",
  },
  {
    id: "5",
    title: "Advanced JavaScript: From Fundamentals to Functional JS",
    description: "Take your JavaScript skills to the next level with advanced concepts and functional programming",
    price: 69.99,
    rating: 4.8,
    students: 7290,
    category: "Web Development",
    image: "/images/course-javascript.png",
    instructor: "Alex Thompson",
    duration: "6 weeks",
    level: "Advanced",
  },
  {
    id: "6",
    title: "Digital Marketing Mastery",
    description: "Learn SEO, social media marketing, email campaigns, and analytics to grow your business online",
    price: 74.99,
    rating: 4.7,
    students: 4850,
    category: "Marketing",
    image: "/images/course-marketing.png",
    instructor: "Jessica Martinez",
    duration: "8 weeks",
    level: "All Levels",
    isBestseller: true,
  },
  {
    id: "7",
    title: "Python for Data Analysis and Visualization",
    description: "Master Python libraries like Pandas, NumPy, and Matplotlib for data analysis and visualization",
    price: 79.99,
    rating: 4.8,
    students: 6120,
    category: "Data Science",
    image: "/images/course-python.png",
    instructor: "Robert Wilson",
    duration: "7 weeks",
    level: "Intermediate",
  },
  {
    id: "8",
    title: "Blockchain Development and Cryptocurrency",
    description: "Learn blockchain fundamentals and build decentralized applications with Ethereum and Solidity",
    price: 99.99,
    rating: 4.6,
    students: 3280,
    category: "Blockchain",
    image: "/images/course-blockchain.png",
    instructor: "Sophia Lee",
    duration: "10 weeks",
    level: "Advanced",
    isNew: true,
  },
]

export const blogPosts: BlogPost[] = [
  {
    id: "1",
    title: "10 Essential Skills Every Web Developer Should Master in 2023",
    slug: "essential-web-developer-skills-2023",
    excerpt:
      "Discover the most in-demand web development skills that will make you stand out in the job market this year.",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nisl vel ultricies lacinia, nisl nisl aliquam nisl, eu aliquam nisl nisl sit amet nisl. Sed euismod, nisl vel ultricies lacinia, nisl nisl aliquam nisl, eu aliquam nisl nisl sit amet nisl.",
    image: "/images/blog-1.png",
    author: {
      name: "Alex Johnson",
      avatar: "/images/testimonial-2.png",
      role: "Senior Web Developer",
    },
    date: "May 15, 2023",
    readTime: 8,
    tags: ["Web Development", "Career", "Programming"],
  },
  {
    id: "2",
    title: "The Future of AI in Education: Transforming How We Learn",
    slug: "future-ai-education",
    excerpt:
      "Explore how artificial intelligence is revolutionizing educational methods and creating personalized learning experiences.",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nisl vel ultricies lacinia, nisl nisl aliquam nisl, eu aliquam nisl nisl sit amet nisl. Sed euismod, nisl vel ultricies lacinia, nisl nisl aliquam nisl, eu aliquam nisl nisl sit amet nisl.",
    image: "/images/blog-2.png",
    author: {
      name: "Sophia Chen",
      avatar: "/images/testimonial-3.png",
      role: "EdTech Researcher",
    },
    date: "April 28, 2023",
    readTime: 10,
    tags: ["AI", "Education", "Technology"],
  },
  {
    id: "3",
    title: "Mastering Data Visualization: Telling Stories with Your Data",
    slug: "mastering-data-visualization",
    excerpt:
      "Learn how to create compelling data visualizations that communicate insights effectively and drive decision-making.",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nisl vel ultricies lacinia, nisl nisl aliquam nisl, eu aliquam nisl nisl sit amet nisl. Sed euismod, nisl vel ultricies lacinia, nisl nisl aliquam nisl, eu aliquam nisl nisl sit amet nisl.",
    image: "/images/blog-3.png",
    author: {
      name: "Michael Rodriguez",
      avatar: "/images/testimonial-4.png",
      role: "Data Scientist",
    },
    date: "May 5, 2023",
    readTime: 12,
    tags: ["Data Science", "Visualization", "Analytics"],
  },
  {
    id: "4",
    title: "The Psychology of Learning: How to Study Smarter, Not Harder",
    slug: "psychology-of-learning",
    excerpt: "Discover evidence-based techniques to improve your learning efficiency and retain information longer.",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nisl vel ultricies lacinia, nisl nisl aliquam nisl, eu aliquam nisl nisl sit amet nisl. Sed euismod, nisl vel ultricies lacinia, nisl nisl aliquam nisl, eu aliquam nisl nisl sit amet nisl.",
    image: "/images/blog-4.png",
    author: {
      name: "Emily Taylor",
      avatar: "/images/testimonial-1.png",
      role: "Cognitive Psychologist",
    },
    date: "April 18, 2023",
    readTime: 9,
    tags: ["Learning", "Psychology", "Productivity"],
  },
  {
    id: "5",
    title: "Building Accessible Websites: A Comprehensive Guide",
    slug: "building-accessible-websites",
    excerpt: "Learn how to create websites that are accessible to everyone, including people with disabilities.",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nisl vel ultricies lacinia, nisl nisl aliquam nisl, eu aliquam nisl nisl sit amet nisl. Sed euismod, nisl vel ultricies lacinia, nisl nisl aliquam nisl, eu aliquam nisl nisl sit amet nisl.",
    image: "/images/blog-5.png",
    author: {
      name: "David Wilson",
      avatar: "/images/testimonial-2.png",
      role: "Accessibility Specialist",
    },
    date: "May 10, 2023",
    readTime: 11,
    tags: ["Web Development", "Accessibility", "UX Design"],
  },
  {
    id: "6",
    title: "From Bootcamp to Job: Navigating Your Tech Career Transition",
    slug: "bootcamp-to-job-transition",
    excerpt:
      "Practical advice for bootcamp graduates looking to break into the tech industry and land their first job.",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nisl vel ultricies lacinia, nisl nisl aliquam nisl, eu aliquam nisl nisl sit amet nisl. Sed euismod, nisl vel ultricies lacinia, nisl nisl aliquam nisl, eu aliquam nisl nisl sit amet nisl.",
    image: "/images/blog-6.png",
    author: {
      name: "Jessica Martinez",
      avatar: "/images/testimonial-3.png",
      role: "Career Coach",
    },
    date: "April 22, 2023",
    readTime: 7,
    tags: ["Career", "Tech Industry", "Job Search"],
  },
]

export const testimonials: Testimonial[] = [
  {
    id: "1",
    name: "Sarah Thompson",
    title: "Web Developer at TechCorp",
    avatar: "/images/testimonial-1.png",
    quote:
      "The web development bootcamp completely transformed my career. The instructors were knowledgeable and supportive, and the curriculum was comprehensive and up-to-date with industry standards. I landed a job within a month of completing the course!",
  },
  {
    id: "2",
    name: "James Wilson",
    title: "Data Analyst at AnalyticsPro",
    avatar: "/images/testimonial-2.png",
    quote:
      "As someone with no prior experience in data science, I was amazed at how quickly I was able to grasp complex concepts through this platform. The hands-on projects and real-world applications made learning engaging and practical.",
  },
  {
    id: "3",
    name: "Emily Rodriguez",
    title: "UX Designer at CreativeStudio",
    avatar: "/images/testimonial-3.png",
    quote:
      "The UI/UX design course exceeded my expectations. The instructor broke down complex design principles into digestible modules, and the community support was invaluable. This course gave me the confidence to transition into a design role.",
  },
  {
    id: "4",
    name: "Michael Chen",
    title: "Mobile Developer at AppWorks",
    avatar: "/images/testimonial-4.png",
    quote:
      "I've taken several online courses before, but none were as comprehensive and well-structured as this one. The React Native course helped me build a portfolio of real apps that impressed employers during my job search.",
  },
]
